### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [12]:
#esempio 1
quadrati = []
for i in range (10): 
    quadrati.append(i**2)
print(quadrati)

#esempio 2
numeri_pari = []
for i in range (20):
    if i % 2 == 0:
        numeri_pari.append(i)
print(numeri_pari)

#esempio 3
swords = ["ciao", "mondo", "python"]
lengths = []
for word in swords:
    lengths.append(len(word))
print(lengths)

#list comprehensions
#1
quadrati_lc = [i**2 for i in range (10)]
print(quadrati_lc)

#2
num_pari_lc = [i for i in range (20) if i % 2 == 0]
print(num_pari_lc)

#3
lengths_lc = [len(word) for word in swords]
print(lengths_lc)





[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[4, 5, 6]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[4, 5, 6]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
import numpy as np
num_primi = np.array([2, 3, 5, 7])
print(len(num_primi))
print (num_primi.size)
#i numeri saranno interi, int64.
print(num_primi.dtype)  
#4
def è_primo(n):
    if n < 2:
        return False
    for i in range(2,int (n**0.5)+1):
        if n%i == 0:
            return False
    return True
num_primi_lc = np.array([x for x in range(11) if è_primo(x)])
print(num_primi)  



4
4
int64
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [19]:
import numpy as np
a = np.arange(1, 6)
b = a[:3]
c = a[::-1]
d= a/c
print(a)
print(b)
print(c)
print(d)

[1 2 3 4 5]
[1 2 3]
[5 4 3 2 1]
[0.2 0.5 1.  2.  5. ]
