### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [1]:
import numpy as np

primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])

maggiori_di_10 = primi[primi > 10]
print("Numeri primi > 10:", maggiori_di_10)

primi_pari = primi[primi % 2 == 0]
print("Numeri primi pari:", primi_pari)


Numeri primi > 10: [11 13 17 19]
Numeri primi pari: [2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [2]:
import numpy as np

a = np.arange(1, 21).reshape(5, 4)  # 5 righe, 4 colonne
print("Array a:\n", a)

b = a[[1, 3], :]
c = a[2, :]  # riga singola

print("Array b (2ª e 4ª riga):\n", b)
print("Array c (3ª riga):", c)

divisione = a / c
print("a / c (per colonna):\n", divisione)


Array a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Array b (2ª e 4ª riga):
 [[ 5  6  7  8]
 [13 14 15 16]]
Array c (3ª riga): [ 9 10 11 12]
a / c (per colonna):
 [[0.11111111 0.2        0.27272727 0.33333333]
 [0.55555556 0.6        0.63636364 0.66666667]
 [1.         1.         1.         1.        ]
 [1.44444444 1.4        1.36363636 1.33333333]
 [1.88888889 1.8        1.72727273 1.66666667]]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [1]:
import numpy as np
a = np.random.rand(10, 3)
distanze = np.abs (a - 0.5)
indici = np.argmin(distanze, axis=1)
piu_vicini = a[np.arange(a.shape[0]), indici]

print("Array originale:\n", a)
print("\nValori più vicini a 0.5 in ogni riga:\n", piu_vicini)

Array originale:
 [[0.98298123 0.0113184  0.26081321]
 [0.29998205 0.58535319 0.30641099]
 [0.72085165 0.24240613 0.8202174 ]
 [0.80547568 0.71055239 0.45548574]
 [0.98942408 0.17300635 0.65026114]
 [0.41688694 0.24010892 0.54220638]
 [0.60780618 0.49866673 0.10259677]
 [0.75993678 0.22707256 0.69539626]
 [0.67103276 0.40577366 0.49303113]
 [0.79073584 0.46911846 0.69097903]]

Valori più vicini a 0.5 in ogni riga:
 [0.26081321 0.58535319 0.72085165 0.45548574 0.65026114 0.54220638
 0.49866673 0.69539626 0.49303113 0.46911846]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [2]:
import numpy as np

# 1. Inserimento dei dati
frequenze = np.array([
    68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 
    162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70
])

# 2. Frequenza cardiaca minima
fc_min = np.min(frequenze)
print("Frequenza cardiaca minima:", fc_min, "bpm")

# 3. Frequenza cardiaca massima
fc_max = np.max(frequenze)
print("Frequenza cardiaca massima:", fc_max, "bpm")

# 4. Percentuale di tempo in esercizio (frequenza > 120)
in_esercizio = frequenze > 120
percentuale_esercizio = np.sum(in_esercizio) / len(frequenze) * 100
print(f"Percentuale del tempo in cui la frequenza era > 120 bpm: {percentuale_esercizio:.2f}%")


Frequenza cardiaca minima: 60 bpm
Frequenza cardiaca massima: 164 bpm
Percentuale del tempo in cui la frequenza era > 120 bpm: 52.38%


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [4]:
import numpy as np

# 1. Vettore stipendi iniziali
stipendi = np.array([50000, 105250, 55000, 89000])
print("1. Costo iniziale del personale:", np.sum(stipendi), "dollari")

# 2. Aumento del 15% per il CEO (stipendio 105250)
index_ceo = np.where(stipendi == 105250)[0][0]
stipendi[index_ceo] *= 1.15
print("2. Stipendi dopo aumento del CEO:", stipendi)

# 3. Controllo se 121037.50 è nel vettore
print("3. 121037.50 è presente nel vettore?", 121037.50 in stipendi)
print("   Valore attuale CEO (con float default):", stipendi[index_ceo])

# 4. Ricreazione con dtype float64 per maggiore precisione
stipendi = np.array([50000, 105250, 55000, 89000], dtype=np.float64)
stipendi[np.where(stipendi == 105250)[0][0]] *= 1.15
print("4. Valore CEO con dtype=float64:", stipendi[1])
print("   121037.50 presente nel vettore?", 121037.50 in stipendi)

# 5. Aumento del 20% per chi guadagna 50000
stipendi[np.where(stipendi == 50000)[0][0]] *= 1.20
print("5. Stipendi dopo aumento impiegata:", stipendi)

# 6. Aumento del 10% agli altri due dipendenti (quelli che non sono CEO né impiegata 50k)
# Troviamo gli indici restanti
restanti = [i for i in range(len(stipendi)) if i not in [0, 1]]  # impiegata e CEO sono [0,1]
stipendi[restanti] *= 1.10
print("6. Stipendi dopo aumenti agli altri due:", stipendi)

# 7. Costo totale finale e calcolo differenza dovuta al CEO
costo_totale_finale = np.sum(stipendi)
print("7. Costo totale dopo tutti gli aumenti:", round(costo_totale_finale, 2), "dollari")

# Calcolo quanto è costato in più il CEO
aumento_ceo = stipendi[1] - 105250
print("   Aumento effettivo del CEO:", round(aumento_ceo, 2), "dollari")


1. Costo iniziale del personale: 299250 dollari
2. Stipendi dopo aumento del CEO: [ 50000 121037  55000  89000]
3. 121037.50 è presente nel vettore? False
   Valore attuale CEO (con float default): 121037
4. Valore CEO con dtype=float64: 121037.49999999999
   121037.50 presente nel vettore? False
5. Stipendi dopo aumento impiegata: [ 60000.  121037.5  55000.   89000. ]
6. Stipendi dopo aumenti agli altri due: [ 60000.  121037.5  60500.   97900. ]
7. Costo totale dopo tutti gli aumenti: 339437.5 dollari
   Aumento effettivo del CEO: 15787.5 dollari


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [5]:
import numpy as np

# 1. Carica i valori di CO2 da file
# Sostituisci 'emissioni_co2.txt' con il nome del tuo file se diverso
co2 = np.loadtxt('emissioni_co2.txt')
print("1. Dati caricati:", co2)

# 2. Valori sopra soglia (18 tonnellate)
sopra_soglia = co2[co2 > 18]
conteggio_sopra = sopra_soglia.size
media_sopra = np.mean(sopra_soglia)
print(f"\n2. Valori sopra 18 tonnellate: {conteggio_sopra}")
print(f"   Valore medio sopra soglia: {media_sopra:.2f} tonnellate/anno")

# 3. Frazione delle emissioni sopra la soglia
frazione_sopra = np.sum(sopra_soglia) / np.sum(co2)
print(f"\n3. Frazione totale delle emissioni sopra soglia: {frazione_sopra:.4f}")


FileNotFoundError: emissioni_co2.txt not found.

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [6]:
import numpy as np

# Matrice survey: [età, reddito, anni di istruzione]
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

# 1. Seleziona solo gli intervistati con almeno 12 anni di istruzione
istruzione_almeno_12 = survey_matrix[survey_matrix[:, 2] >= 12]
print("1. Intervistati con almeno 12 anni di istruzione:\n", istruzione_almeno_12)

# 2. Seleziona i redditi degli intervistati con almeno 12 anni di istruzione
redditi_12plus = survey_matrix[survey_matrix[:, 2] >= 12][:, 1]
print("\n2. Redditi di chi ha almeno 12 anni di istruzione:", redditi_12plus)

# 3. Calcola il reddito medio degli intervistati con almeno 12 anni di istruzione
reddito_medio = np.mean(redditi_12plus)
print("\n3. Reddito medio (>=12 anni istruzione):", round(reddito_medio, 2))


1. Intervistati con almeno 12 anni di istruzione:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]

2. Redditi di chi ha almeno 12 anni di istruzione: [52000 63000 58000]

3. Reddito medio (>=12 anni istruzione): 57666.67


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [7]:
import numpy as np

# Array già fornito
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

# 1. Rimuovi i valori errati (999)
ages_clean = ages[ages != 999]

# 2. Trova l'età del cittadino più anziano (senza outliers)
piu_anziano = np.max(ages_clean)

# 3. Output
print("Numero di dati iniziali:", ages.size)
print("Numero di dati corretti:", ages_clean.size)
print("Età del cittadino più anziano:", piu_anziano)






Numero di dati iniziali: 500
Numero di dati corretti: 486
Età del cittadino più anziano: 112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [9]:
import numpy as np

# Lista di parole fornite
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

# Estrai 5 parole con reinserimento
parole_estratte = np.random.choice(lista_parole, size=5, replace=True)

# Frase con gli spazi riempiti
frase = f"""
In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {parole_estratte[0]} che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il {parole_estratte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{parole_estratte[2]}".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parole_estratte[3]}. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 

Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parole_estratte[4]}!"  

Ci fu grande gioia e celebrazione.
"""

# Output della storia generata
print(frase)




In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico IGNORANZA che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "HOT DOG".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BENEFICIARIO. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 

Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza BIOGRAFIA!"  

Ci fu grande gioia e celebrazione.



NameError: name 'lista_parole' is not defined

Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."